# ============================================================================
# Instant Release Configuration
# ============================================================================

# --- GIT CONFIGURATION ---
git:
  user-name: "github-actions[bot]"
  user-email: "github-actions[bot]@github.com"
  auto-commit: true
  auto-push: true
  target-branch: "main"

# --- VERSIONING ---
versioning:
  initial-version: "v0.1.0"
  bump: "auto"                    # auto | major | minor | patch | none
  detect-bump: true
  
  # Semantic commit indicators
  indicators:
    major: "BREAKING CHANGE|!:"      # Peut être multi-ligne séparé par |
    minor: "feat|feature"
    patch: "fix|bugfix"
  
  # Prefix pour les tags
  version-prefix: "v"
  verify-tag-exists: true

# --- CHANGELOG ---
changelog:
  generate: true
  file: "CHANGELOG.md"
  template: "templates/changelog-default.hbs"
  append-mode: "prepend"          # prepend | append | replace
  include-contributors: true
  include-stats: true

# --- RELEASE ---
release:
  create-tag: true
  create-release: true
  release-draft: false
  release-prerelease: false
  prerelease-suffix: ""           # alpha | beta | rc
  tag-delete-on-failure: true

# --- BUILD ---
build:
  enabled: true
  command: "npm run build"
  artifact-path: "dist"
  upload-artifact: false

# --- TESTS ---
tests:
  enabled: true
  unit-tests-command: "npm test"
  coverage-threshold: 80
  lint-enabled: true
  lint-command: "npm run lint"

# --- SECURITY ---
security:
  dependency-scan: true
  secret-scan: false
  commit-signature-check: false

# --- DEPLOYMENT ---
deployment:
  enabled: false
  environment: "staging"
  command: "npm run deploy"
  post-deploy-validation: false
  post-deploy-check-url: ""

# --- WEBHOOKS ---
webhooks:
  pre-flight:
    enabled: false
    url: ""
    retry-attempts: 3
    timeout: 30
  
  post-release:
    enabled: false
    url: ""
    retry-attempts: 3
    timeout: 30

# --- PLUGINS ---
plugins:
  pre-flight:
    enabled: false
    script: ""
    timeout: 300
  
  post-release:
    enabled: false
    script: ""
    timeout: 300

# --- DEBUG & OPTIONS ---
debug: true
dry-run: false