name: 'Instant Release - CI/CD Framework'
description: 'Modular GitHub Action for complete CI/CD automation'

inputs:
  # Git & Config (REQUIRED)
  github-token:
    description: 'GitHub token with contents:write permission'
    required: true
  git-user-name:
    description: 'Git user name for commits'
    default: 'github-actions[bot]'
  git-user-email:
    description: 'Git user email'
    default: 'github-actions[bot]@github.com'
  
  # Versioning
  bump:
    description: 'Version bump type: auto|major|minor|patch'
    default: 'auto'
  generate-changelog:
    description: 'Generate changelog'
    default: 'true'
  create-tag:
    description: 'Create Git tag'
    default: 'true'
  create-release:
    description: 'Create GitHub Release'
    default: 'true'
  
  # Build
  build-enabled:
    description: 'Enable build step'
    default: 'true'
  build-command:
    description: 'Build command'
    default: 'npm run build'
  
  # Tests
  tests-enabled:
    description: 'Enable tests'
    default: 'true'
  unit-tests-command:
    description: 'Unit tests command'
    default: 'npm test'
  coverage-threshold:
    description: 'Minimum coverage percentage'
    default: '80'
  
  # Security
  dependency-scan-enabled:
    description: 'Enable dependency scanning'
    default: 'true'
  secret-scan-enabled:
    description: 'Enable secret scanning'
    default: 'false'
  
  # Deployment
  deploy-enabled:
    description: 'Enable deployment'
    default: 'false'
  deploy-command:
    description: 'Deploy command'
  
  # Webhooks & Plugins
  webhook-post-release-enabled:
    description: 'Enable post-release webhook'
    default: 'false'
  webhook-post-release-url:
    description: 'Post-release webhook URL'
  plugin-post-release-enabled:
    description: 'Enable post-release plugin'
    default: 'false'
  plugin-post-release-script:
    description: 'Post-release plugin script path'
  
  # Debug & Dry-run
  debug:
    description: 'Enable debug mode'
    default: 'false'
  dry-run:
    description: 'Enable dry-run mode'
    default: 'false'

outputs:
  current-version:
    description: 'Current version created'
    value: ${{ steps.version.outputs.current-version }}
  bump-type:
    description: 'Bump type applied'
    value: ${{ steps.version.outputs.bump-type }}
  tag-created:
    description: 'Whether tag was created'
    value: ${{ steps.tag.outputs.tag-created }}
  changelog-generated:
    description: 'Whether changelog was generated'
    value: ${{ steps.changelog.outputs.changelog-generated }}
  release-url:
    description: 'GitHub Release URL'
    value: ${{ steps.release.outputs.release-url }}
  deployment-status:
    description: 'Deployment status'
    value: ${{ steps.deploy.outputs.deployment-status }}

runs:
  using: 'composite'
  steps:
    # Pre-flight
    - name: Pre-flight checks
      run: ${{ github.action_path }}/scripts/pre-flight.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DEBUG: ${{ inputs.debug }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    # Webhook pre-flight
    - name: Webhook pre-flight
      if: ${{ inputs.webhook-pre-flight-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/webhook-call.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook-pre-flight-url }}
        WEBHOOK_EVENT: 'pre-flight'
        WEBHOOK_TIMEOUT: ${{ inputs.webhook-timeout }}
    
    # Plugin pre-flight
    - name: Plugin pre-flight
      if: ${{ inputs.plugin-pre-flight-enabled == 'true' }}
      run: |
        bash "${{ inputs.plugin-pre-flight-script }}" \
          "${{ inputs.github-token }}" \
          "${{ inputs.config-path }}" \
          "${{ inputs.debug }}"
      shell: bash
      timeout-minutes: ${{ inputs.plugin-timeout }}
    
    # Build
    - name: Build
      if: ${{ inputs.build-enabled == 'true' }}
      run: ${{ inputs.build-command }}
      shell: bash
    
    # Tests
    - name: Unit Tests
      if: ${{ inputs.tests-enabled == 'true' }}
      run: ${{ inputs.unit-tests-command }}
      shell: bash
    
    - name: Coverage Check
      if: ${{ inputs.tests-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/coverage-check.sh
      shell: bash
      env:
        COVERAGE_THRESHOLD: ${{ inputs.coverage-threshold }}
        COVERAGE_FILE: ${{ inputs.coverage-file-path }}
    
    - name: Lint
      if: ${{ inputs.lint-enabled == 'true' }}
      run: ${{ inputs.lint-command }}
      shell: bash
    
    # Security
    - name: Dependency Scan
      if: ${{ inputs.dependency-scan-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/dependency-scan.sh
      shell: bash
      env:
        SCAN_TOOL: ${{ inputs.dependency-scan-tool }}
        SEVERITY_THRESHOLD: ${{ inputs.dependency-severity-threshold }}
    
    - name: Secret Scan
      if: ${{ inputs.secret-scan-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/secret-scan.sh
      shell: bash
    
    - name: SAST Analysis
      if: ${{ inputs.sast-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/sast-analysis.sh
      shell: bash
      env:
        SAST_TOOL: ${{ inputs.sast-tool }}
    
    # Versioning
    - name: Calculate Version
      id: version
      run: ${{ github.action_path }}/scripts/calculate-version.sh
      shell: bash
      env:
        BUMP: ${{ inputs.bump }}
        VERSION: ${{ inputs.version }}
        INITIAL: ${{ inputs.initial }}
        MAJOR_INDICATOR: ${{ inputs.major-indicator }}
        MINOR_INDICATOR: ${{ inputs.minor-indicator }}
        PATCH_INDICATOR: ${{ inputs.patch-indicator }}
    
    - name: Sync Version Files
      if: ${{ inputs.sync-version != '' }}
      run: ${{ github.action_path }}/scripts/sync-version.sh
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.current-version }}
        SYNC_PATHS: ${{ inputs.sync-version }}
    
    # Changelog
    - name: Generate Changelog
      if: ${{ inputs.generate-changelog == 'true' }}
      id: changelog
      run: ${{ github.action_path }}/scripts/generate-changelog.sh
      shell: bash
      env:
        CHANGELOG_FILE: ${{ inputs.changelog-file }}
        CHANGELOG_TEMPLATE: ${{ inputs.changelog-template }}
        VERSION: ${{ steps.version.outputs.current-version }}
    
    # Tagging & Release
    - name: Create Tag
      if: ${{ inputs.create-tag == 'true' }}
      id: tag
      run: ${{ github.action_path }}/scripts/create-tag.sh
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.current-version }}
        VERSION_PREFIX: ${{ inputs.version-prefix }}
        TAG_SIGNATURE: ${{ inputs.tag-signature }}
        GPG_KEY: ${{ inputs.gpg-key }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    - name: Auto Commit
      if: ${{ inputs.auto-commit == 'true' && inputs.create-tag == 'true' }}
      run: ${{ github.action_path }}/scripts/auto-commit.sh
      shell: bash
      env:
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
        COMMIT_MESSAGE: ${{ inputs.auto-commit-message }}
        VERSION: ${{ steps.version.outputs.current-version }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    - name: Auto Push
      if: ${{ inputs.auto-push == 'true' && inputs.create-tag == 'true' }}
      run: ${{ github.action_path }}/scripts/auto-push.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    - name: Create Release
      if: ${{ inputs.create-release == 'true' && inputs.create-tag == 'true' }}
      id: release
      run: ${{ github.action_path }}/scripts/create-release.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TAG: ${{ steps.tag.outputs.tag-name }}
        RELEASE_NOTES: ${{ steps.changelog.outputs.release-notes }}
        DRAFT: ${{ inputs.release-draft }}
        PRERELEASE: ${{ inputs.release-prerelease }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    # Deployment
    - name: Pre-Deploy Check
      if: ${{ inputs.deploy-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/pre-deploy-check.sh
      shell: bash
    
    - name: Deploy
      if: ${{ inputs.deploy-enabled == 'true' }}
      id: deploy
      run: ${{ inputs.deploy-command }}
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.deploy-env }}
        VERSION: ${{ steps.version.outputs.current-version }}
        DRY_RUN: ${{ inputs.dry-run }}
    
    - name: Post-Deploy Validation
      if: ${{ inputs.post-deploy-validation == 'true' && inputs.deploy-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/post-deploy-validation.sh
      shell: bash
      env:
        CHECK_URL: ${{ inputs.post-deploy-check-url }}
        TIMEOUT: 300
    
    # Reporting
    - name: Generate Reports
      if: ${{ always() }}
      run: ${{ github.action_path }}/scripts/generate-reports.sh
      shell: bash
      env:
        GENERATE_COMPLIANCE: ${{ inputs.generate-compliance-report }}
        GENERATE_DEPLOYMENT: ${{ inputs.generate-deployment-report }}
        VERSION: ${{ steps.version.outputs.current-version }}
    
    # Webhook post-release
    - name: Webhook post-release
      if: ${{ success() && inputs.webhook-post-release-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/webhook-call.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook-post-release-url }}
        WEBHOOK_EVENT: 'post-release'
        VERSION: ${{ steps.version.outputs.current-version }}
        TAG: ${{ steps.tag.outputs.tag-name }}
        RELEASE_URL: ${{ steps.release.outputs.release-url }}
    
    # Plugin post-release
    - name: Plugin post-release
      if: ${{ success() && inputs.plugin-post-release-enabled == 'true' }}
      run: |
        bash "${{ inputs.plugin-post-release-script }}" \
          "${{ steps.version.outputs.current-version }}" \
          "${{ steps.tag.outputs.tag-name }}" \
          "${{ steps.release.outputs.release-url }}" \
          "${{ inputs.dry-run }}"
      shell: bash
      timeout-minutes: ${{ inputs.plugin-timeout }}
    
    # Error handling - Webhook on-failure
    - name: Webhook on-failure
      if: ${{ failure() && inputs.webhook-on-failure-enabled == 'true' }}
      run: ${{ github.action_path }}/scripts/webhook-call.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook-on-failure-url }}
        WEBHOOK_EVENT: 'on-failure'
        ERROR_MESSAGE: ${{ job.status }}
        PHASE: 'workflow'
    
    # Error handling - Plugin on-failure
    - name: Plugin on-failure
      if: ${{ failure() && inputs.plugin-on-failure-enabled == 'true' }}
      run: |
        bash "${{ inputs.plugin-on-failure-script }}" \
          "${{ job.status }}" \
          "workflow" \
          "1"
      shell: bash
      timeout-minutes: ${{ inputs.plugin-timeout }}
      continue-on-error: true
    
    # Cleanup
    - name: Upload Artifacts
      if: ${{ always() && inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: |
          ${{ inputs.changelog-file }}
          ${{ steps.version.outputs.version-file-path }}
        retention-days: ${{ inputs.artifact-retention-days }}